import { chromium } from 'playwright-core'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const artifacts = path.join(root, 'artifacts')
await mkdir(artifacts, { recursive: true })
const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
const failedResponses = []
page.on('console', (message) => message.type() === 'error' && errors.push(message.text()))
page.on('pageerror', (error) => errors.push(error.message))
page.on('response', (response) => response.status() >= 400 && failedResponses.push(`${response.status()} ${response.url()}`))
const archiveUrl = process.env.SMOKE_URL ?? 'http://127.0.0.1:4173'
await page.goto(archiveUrl, { waitUntil: 'networkidle' })

if (await page.locator('.character-card').count() !== 24) throw new Error('Expected first 24 restored roster cards.')
for (const forbidden of ['Add build', 'About', 'Diagnostics', 'Edit build', 'Duplicate', 'Delete', 'Download backup']) {
  if (await page.getByText(forbidden, { exact: true }).count()) throw new Error(`Forbidden public control found: ${forbidden}`)
}
await page.screenshot({ path: path.join(artifacts, 'public-desktop.png'), fullPage: true })
await page.getByLabel('Filter by series').selectOption({ label: 'Solo Leveling' })
if (await page.locator('.character-card').count() < 4) throw new Error('Solo Leveling roster was not restored.')
await page.getByLabel('Filter by series').selectOption('')
await page.getByLabel('Filter by series').selectOption({ label: 'The God of High School' })
if (await page.locator('.character-card').count() < 2) throw new Error('God of High School roster was not restored.')
await page.getByLabel('Filter by series').selectOption('')
await page.getByLabel('Search builds').fill('James Lee')
await page.waitForTimeout(250)
if (await page.getByText('Unlock in a character pack', { exact: true }).count() !== 1) throw new Error('James Lee should be locked in the public archive.')
if (await page.locator('.character-card .card-primary-bloodline').count()) throw new Error('Locked premium loadout data leaked into the public card.')
await page.getByLabel('Search builds').fill('Zack Lee')
await page.waitForTimeout(250)
await page.getByRole('button', { name: 'Quick view' }).click()
await page.getByRole('dialog', { name: 'Zack Lee quick view' }).waitFor()
await page.getByRole('button', { name: 'Open full build' }).click()
await page.locator('.full-build-page').waitFor()
if (!/\/build\/zack-lee/.test(page.url())) throw new Error('Free full build route was not created.')
await page.getByLabel('Selected profile').selectOption('zack-lee-2x2')
await page.waitForFunction(() => document.querySelector('#section-bloodlines h3')?.textContent?.includes('2 slot'))
await page.screenshot({ path: path.join(artifacts, 'public-detail-2-slot.png'), fullPage: false })
await page.getByRole('button', { name: 'Back to archive' }).click()
await page.getByLabel('Search builds').fill('')
await page.waitForTimeout(250)
await page.getByRole('button', { name: '96' }).click()
if (await page.locator('.character-card').count() !== 96) throw new Error('Expected 96 records on the first large page.')
await page.getByLabel('Next page').click()
if (await page.locator('.character-card').count() !== 4) throw new Error('Expected four records on page two of the 100-character archive.')
await page.getByLabel('Previous page').click()
await page.getByRole('button', { name: 'Tier Lists' }).click()
await page.getByText('Personal community tier list — not an official archive ranking.').first().waitFor()
if (await page.locator('.tier-chip').count() !== 100) throw new Error('Tier Lists did not receive the complete roster.')
await page.getByRole('button', { name: 'Suggestions' }).click()
await page.getByLabel('Character name').fill('Test Fighter')
await page.getByRole('button', { name: 'Copy suggestion' }).click()
await page.getByRole('button', { name: 'Builds', exact: true }).click()
await page.getByLabel('Search builds').fill('Zack Lee')
await page.waitForTimeout(250)
await page.getByLabel('Add Zack Lee to comparison').click()
await page.getByRole('button', { name: 'Table view' }).click()
if (!(await page.getByText('Zack Lee', { exact: true }).evaluateAll((nodes) => nodes.some((node) => {
  const style = getComputedStyle(node)
  return style.display !== 'none' && style.visibility !== 'hidden' && node.getBoundingClientRect().width > 0
})))) throw new Error('Zack Lee is missing from Database.')
await page.getByRole('button', { name: 'Builds', exact: true }).click()
await page.getByLabel('Search builds').fill('Vasco')
await page.waitForTimeout(250)
await page.getByLabel('Add Vasco to comparison').click()
await page.getByRole('button', { name: 'Compare' }).click()
await page.getByRole('heading', { name: 'Zack Lee', exact: true }).waitFor()
await page.getByRole('heading', { name: 'Vasco', exact: true }).waitFor()
await page.locator('.compare-panel button[aria-label="Close comparison"]').click()
await page.getByRole('button', { name: 'My Inventory' }).click()
await page.getByLabel('Search inventory').fill('Ryuji-Kenichi')
if (await page.locator('.inventory-card').filter({ hasText: 'Ryuji-Kenichi' }).count() !== 1) throw new Error('Free-build Bloodlines are missing from My Inventory.')
await page.getByRole('button', { name: 'Builds', exact: true }).click()

for (const width of [1366, 1920, 2560, 320, 375, 430]) {
  await page.setViewportSize({ width, height: width < 500 ? 844 : 1000 })
  if (width < 500) {
    await page.getByLabel('Toggle navigation').click()
    if (await page.getByRole('button', { name: 'My Inventory' }).count() !== 1) throw new Error(`Mobile navigation incomplete at ${width}px`)
    await page.getByLabel('Toggle navigation').click()
  }
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  if (overflow) throw new Error(`Horizontal overflow at ${width}px`)
}
await page.setViewportSize({ width: 375, height: 844 })
await page.screenshot({ path: path.join(artifacts, 'public-mobile.png'), fullPage: true })
const archiveLocation = new URL(archiveUrl)
const archiveBase = archiveLocation.pathname.replace(/\/$/, '')
await page.goto(`${archiveLocation.origin}${archiveBase}/build/goo-kim`, { waitUntil: 'networkidle' })
await page.getByRole('heading', { name: 'Goo Kim', exact: true }).waitFor()
if (await page.getByText('Unlock in a character pack', { exact: true }).count() < 1) throw new Error('Direct Goo build route should remain locked.')
if (await page.getByText('Wind-Kenjutsu', { exact: true }).count()) throw new Error('Direct Goo build route leaked premium Kenjutsu data.')
if (errors.length) throw new Error(`Console errors: ${errors.join(' | ')}; failed responses: ${failedResponses.join(' | ')}`)
console.log(JSON.stringify({ url: page.url(), roster: 100, firstPageCards: 24, tierCharacters: 100, consoleErrors: 0, viewports: [320, 375, 430, 1366, 1920, 2560], screenshots: ['public-desktop.png', 'public-detail-2-slot.png', 'public-mobile.png'] }))
await browser.close()
